20-rails-validations/config/routes.rb
Rails.application.routes.draw do
  get "/doggos/:id/spells", to: 'doggos#spells', as: 'dog_spell_for_what'
  resources :doggo_spells
  resources :spells
  resources :doggos
  # get '/doggos', to: 'doggos#index', as: "doggos"
  # get '/doggos/:id', to: 'doggos#show', as: "doggo"
  # get '/doggos/new', to: 'doggos#new', as: "new_doggo"
  # post '/doggos', to: 'doggos#create'
  # get '/doggos/:id/edit', to: 'doggos#edit', as: "edit_doggo"
  # put '/doggos/:id', to: 'doggos#update'
  # patch '/doggos/:id', to: 'doggos#update'
  # delete '/doggos/:id', to: 'doggos#destroy'

end

20-rails-validations/app/models/doggo.rb
class Doggo < ApplicationRecord
  has_many :doggo_spells, dependent: :destroy
  has_many :spells, through: :doggo_spells

  def string_name
    "#{self.name}!!!!"
  end
end

20-rails-validations/app/models/doggo_spell.rb
class DoggoSpell < ApplicationRecord
  belongs_to :doggo
  belongs_to :spell
end

20-rails-validations/app/models/spell.rb
class Spell < ApplicationRecord
  has_many :doggo_spells, dependent: :destroy
  has_many :doggos, through: :doggo_spells

  validates :incantation, :description, presence: true, uniqueness: true
  validates :intensity, presence: true

  validates :intensity, numericality: {greater_than: 0}
  validate :please_dont_say_he_who_must_not_be_named

  def please_dont_say_he_who_must_not_be_named
    if self.incantation.downcase.include?("voldemort")
      self.errors.add(:incantation, "must not include Lord Voldy.")
    end
  end


  # validates :incantation
end

20-rails-validations/app/controllers/doggo_spells_controller.rb
class DoggoSpellsController < ApplicationController

  def new
    @doggo_spell = DoggoSpell.new
    @doggos = Doggo.all
    @spells = Spell.all
  end

  def create
    @doggo_spell = DoggoSpell.create(doggo_spell_params)
    redirect_to @doggo_spell.doggo
  end

  private
  def doggo_spell_params
    params.require(:doggo_spell).permit(:doggo_id, :spell_id, :location)
  end
end

20-rails-validations/app/controllers/doggos_controller.rb
class DoggosController < ApplicationController
  before_action :find_doggo, only: [:show, :edit, :update, :destroy, :spells]

  def index
    if params[:search]
      @doggos = Doggo.where("name like ?", "%#{params[:search]}%")
    else
      @doggos = Doggo.all
    end
    # render :index
  end

  def show
    @doggo_spell = DoggoSpell.new
    @spells = Spell.all
  end

  def new
    @doggo = Doggo.new
    @spells = Spell.all
  end

  def create
    # byebug
    @doggo = Doggo.create(doggo_params)
    @doggo.spell_ids = params[:doggo][:spell_ids]
    # redirect_to "/doggos/#{@doggo.id}"
    # redirect_to doggo_path(@doggo)
    redirect_to @doggo
  end

  def edit
  end

  def update
    @doggo.update(doggo_params)
    redirect_to @doggo
  end

  def destroy
    @doggo.destroy
    redirect_to doggos_path
  end

  def spells
    @doggo_spell = DoggoSpell.new
    @spells = Spell.all
  end

  private

  def doggo_params
    params.require(:doggo).permit(:name, :house, :wand_core)
  end

  def find_doggo
    @doggo = Doggo.find(params[:id])
  end













end

20-rails-validations/app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :find_spell, only: [:show, :edit, :update, :destroy]

  def index
    @spells = Spell.all
  end

  def show
  end

  def new
    @spell = Spell.new
  end

  def create
    @spell = Spell.create(spell_params)
    if @spell.valid?
      redirect_to @spell
    else
      flash[:errors] = @spell.errors.full_messages
      redirect_to new_spell_path
    end
  end

  def edit
  end

  def update
    if @spell.update(spell_params)
      redirect_to @spell
    else
      flash[:errors] = @spell.errors.full_messages
      redirect_to edit_spell_path(@spell)
    end

  end

  def destroy
    @spell.destroy
    redirect_to spells_path
  end

  private

  def spell_params
    params.require(:spell).permit(:description, :incantation, :intensity)
  end

  def find_spell
    @spell = Spell.find(params[:id])
  end

end

20-rails-validations/app/helpers/doggo_spells_helper.rb
module DoggoSpellsHelper
end

20-rails-validations/app/helpers/doggos_helper.rb
module DoggosHelper
end

20-rails-validations/app/helpers/spells_helper.rb
module SpellsHelper
end

20-rails-validations/app/views/doggo_spells/new.html.erb
<h1>Logging a Doggo Spell</h1>

<%= form_for(@doggo_spell) do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :doggo_id %>
  <%= f.collection_select(:doggo_id, @doggos, :id , :name) %>

  <%= f.label :spell_id %>
  <%= f.collection_select :spell_id, @spells, :id, :incantation %>

  <%= f.submit %>

<% end %>

20-rails-validations/app/views/doggos/edit.html.erb
<h1>Editing Doggo</h1>

<%= form_for @doggo do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :wand_core %>
  <%= f.text_field :wand_core %>
  <%= f.label :house %>
  <%= f.text_field :house %>
  <%= f.submit %>

<% end %>

20-rails-validations/app/views/doggos/index.html.erb
<h1>Hello! This is a list of all the doggos. </h1>

<%= form_tag "/doggos", method: :get do %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search!!" %>
<% end %>

<%= link_to "Create a new doggo", new_doggo_path %>

<ul>
  <% @doggos.each do |doggy| %>
    <li>
      <%# link_to doggy.name, "/doggos/#{doggy.id}" %>
      <%# link_to doggy.name, doggo_path(doggy.id) %>
      <%# link_to doggy.name, doggo_path(doggy) %>
      <%= link_to doggy.name, doggy %>
    </li>
  <% end %>
</ul>

20-rails-validations/app/views/doggos/new.html.erb
<h1>Form to House this Doggo.</h1>

<%= form_for @doggo do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :wand_core %>
  <%= f.text_field :wand_core %>
  <%= f.label :house %>
  <%= f.text_field :house %>
  <%= f.label :spells %>
  <%= f.collection_check_boxes :spell_ids, @spells, :id, :incantation %>
  <%= f.submit %>

<% end %>

20-rails-validations/app/views/doggos/show.html.erb
<h1>Show Page</h1>

<%= link_to "Take us to the kennel", doggos_path %>

<p>
  Name: <%= @doggo.name %>
</p>
<p>
  House: <%= @doggo.house %>
</p>
<p>
  Wand Core: <%= @doggo.wand_core %>
</p>

<%= button_to "Avada Kedavra", @doggo, method: :delete %>
<%= link_to "Edit this Doggo", edit_doggo_path(@doggo) %>

<h2>All the Spells</h2>

<ul>
  <% @doggo.doggo_spells.each do |doggo_spell| %>
    <li>
      <%= link_to "#{doggo_spell.spell.incantation} - #{doggo_spell.location}", spell_path(doggo_spell.spell_id) %>
    </li>
  <% end %>
</ul>

<%= link_to "Log a Spell", dog_spell_for_what_path(@doggo) %>

<h2>Log a Spell</h2>

<%= form_for(@doggo_spell) do |f| %>
  <%= f.hidden_field :doggo_id, value: @doggo.id %>

  <%= f.label :location %>
  <%= f.text_field :location %>


  <%= f.label :spell_id %>
  <%= f.collection_select :spell_id, @spells, :id, :incantation %>

  <%= f.submit %>
<% end %>














<!--  -->

20-rails-validations/app/views/doggos/spells.html.erb
<h1>Creating a Spell for <%= @doggo.name %> </h1>

<%= form_for(@doggo_spell) do |f| %>
  <%= f.hidden_field :doggo_id, value: @doggo.id %>

  <%= f.label :location %>
  <%= f.text_field :location %>


  <%= f.label :spell_id %>
  <%= f.collection_select :spell_id, @spells, :id, :incantation %>

  <%= f.submit %>
<% end %>

20-rails-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogwartsRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>